PMX_COMMON_BONE_NAMES_MOCOPI_MAPPING = {
    # root/torso_1/torso_2/torso_3/torso_4/torso_5/torso_6/torso_7/neck_1/neck_2/head
    "全ての親": ("root",),
    "センター": (None,),
    "下半身": (None,),
    "上半身": (
        "torso_1",
        "torso_2",
        "torso_3",
        "torso_4",
    ),
    "上半身2": (
        "torso_5",
        "torso_6",
        "torso_7",
    ),
    "首": (
        "neck_1",
        "neck_2",
    ),
    "頭": ("head",),
    "左目": (None,),
    "右目": (None,),
    "両目": (None,),
    # root/torso_1/torso_2/torso_3/torso_4/torso_5/torso_6/torso_7/l_shoulder/l_up_arm/l_low_arm/l_hand
    "左肩": ("l_shoulder",),
    "左腕": ("l_up_arm",),
    "左ひじ": ("l_low_arm",),
    "左手首": ("l_hand",),
    # root/torso_1/torso_2/torso_3/torso_4/torso_5/torso_6/torso_7/r_shoulder/r_up_arm/r_low_arm/r_hand
    "右肩": ("r_shoulder",),
    "右腕": ("r_up_arm",),
    "右ひじ": ("r_low_arm",),
    "右手首": ("r_hand",),
    # root/l_up_leg/l_low_leg/l_foot/l_toes
    "左足": ("l_up_leg",),
    "左ひざ": ("l_low_leg",),
    "左足首": ("l_foot",),
    "左つま先": ("l_toes",),
    # root/r_up_leg/r_low_leg/r_foot/r_toes
    "右足": ("r_up_leg",),
    "右ひざ": ("r_low_leg",),
    "右足首": ("r_foot",),
    "右つま先": ("r_toes",),
    "左親指１": (None,),
    "左親指２": (None,),
    "左人指１": (None,),
    "左人指２": (None,),
    "左人指３": (None,),
    "左中指１": (None,),
    "左中指２": (None,),
    "左中指３": (None,),
    "左薬指１": (None,),
    "左薬指２": (None,),
    "左薬指３": (None,),
    "左小指１": (None,),
    "左小指２": (None,),
    "左小指３": (None,),
    "右親指１": (None,),
    "右親指２": (None,),
    "右人指１": (None,),
    "右人指２": (None,),
    "右人指３": (None,),
    "右中指１": (None,),
    "右中指２": (None,),
    "右中指３": (None,),
    "右薬指１": (None,),
    "右薬指２": (None,),
    "右薬指３": (None,),
    "右小指１": (None,),
    "右小指２": (None,),
    "右小指３": (None,),
}
